/**
 * RBAC (Role-Based Access Control) Permission Matrix
 */

export const PERMISSIONS = {
  // Receivables
  RECEIVABLE_VIEW: 'receivable.view',
  RECEIVABLE_CREATE: 'receivable.create',
  RECEIVABLE_EDIT: 'receivable.edit',
  RECEIVABLE_APPROVE: 'receivable.approve',
  RECEIVABLE_DELETE: 'receivable.delete',
  RECEIVABLE_PAYMENT: 'receivable.payment',

  // Payables
  PAYABLE_VIEW: 'payable.view',
  PAYABLE_CREATE: 'payable.create',
  PAYABLE_EDIT: 'payable.edit',
  PAYABLE_APPROVE: 'payable.approve',
  PAYABLE_DELETE: 'payable.delete',
  PAYABLE_PAYMENT: 'payable.payment',

  // Commitments
  COMMITMENT_VIEW: 'commitment.view',
  COMMITMENT_CREATE: 'commitment.create',
  COMMITMENT_EDIT: 'commitment.edit',
  COMMITMENT_DELETE: 'commitment.delete',

  // Government Loans
  LOAN_VIEW: 'loan.view',
  LOAN_CREATE: 'loan.create',
  LOAN_EDIT: 'loan.edit',
  LOAN_APPROVE: 'loan.approve',
  LOAN_DISBURSE: 'loan.disburse',
  LOAN_CLEAR: 'loan.clear',
  LOAN_DELETE: 'loan.delete',

  // Budget
  BUDGET_VIEW: 'budget.view',
  BUDGET_CREATE: 'budget.create',
  BUDGET_ADJUST: 'budget.adjust',
  BUDGET_APPROVE: 'budget.approve',
  BUDGET_OVERRIDE: 'budget.override',

  // Revenue
  REVENUE_VIEW: 'revenue.view',
  REVENUE_CREATE: 'revenue.create',
  REVENUE_EDIT: 'revenue.edit',
  REVENUE_DELETE: 'revenue.delete',

  // Cash & Bank
  BANK_VIEW: 'bank.view',
  BANK_TRANSACT: 'bank.transact',
  BANK_RECONCILE: 'bank.reconcile',
  BANK_DAILY_CLOSE: 'bank.daily_close',
  BANK_PERIOD_CLOSE: 'bank.period_close',
  BANK_PERIOD_REOPEN: 'bank.period_reopen',

  // Reports & Analytics
  REPORT_VIEW: 'report.view',
  REPORT_EXPORT: 'report.export',

  // Audit
  AUDIT_VIEW: 'audit.view',

  // Settings & Master Data
  MASTER_VIEW: 'master.view',
  MASTER_EDIT: 'master.edit',
  USER_MANAGE: 'user.manage',
  ROLE_MANAGE: 'role.manage',
} as const;

export type PermissionCode = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLE_DEFAULT_PERMISSIONS: Record<string, PermissionCode[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: Object.values(PERMISSIONS),
  CFO: [
    PERMISSIONS.RECEIVABLE_VIEW,
    PERMISSIONS.RECEIVABLE_APPROVE,
    PERMISSIONS.PAYABLE_VIEW,
    PERMISSIONS.PAYABLE_APPROVE,
    PERMISSIONS.COMMITMENT_VIEW,
    PERMISSIONS.LOAN_VIEW,
    PERMISSIONS.LOAN_APPROVE,
    PERMISSIONS.BUDGET_VIEW,
    PERMISSIONS.BUDGET_APPROVE,
    PERMISSIONS.BUDGET_OVERRIDE,
    PERMISSIONS.REVENUE_VIEW,
    PERMISSIONS.BANK_VIEW,
    PERMISSIONS.BANK_PERIOD_CLOSE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_VIEW,
  ],
  FINANCE: [
    PERMISSIONS.RECEIVABLE_VIEW,
    PERMISSIONS.RECEIVABLE_CREATE,
    PERMISSIONS.RECEIVABLE_EDIT,
    PERMISSIONS.RECEIVABLE_PAYMENT,
    PERMISSIONS.PAYABLE_VIEW,
    PERMISSIONS.PAYABLE_CREATE,
    PERMISSIONS.PAYABLE_EDIT,
    PERMISSIONS.PAYABLE_PAYMENT,
    PERMISSIONS.COMMITMENT_VIEW,
    PERMISSIONS.COMMITMENT_CREATE,
    PERMISSIONS.COMMITMENT_EDIT,
    PERMISSIONS.LOAN_VIEW,
    PERMISSIONS.LOAN_CREATE,
    PERMISSIONS.LOAN_EDIT,
    PERMISSIONS.LOAN_DISBURSE,
    PERMISSIONS.LOAN_CLEAR,
    PERMISSIONS.REVENUE_VIEW,
    PERMISSIONS.REVENUE_CREATE,
    PERMISSIONS.REVENUE_EDIT,
    PERMISSIONS.BANK_VIEW,
    PERMISSIONS.BANK_TRANSACT,
    PERMISSIONS.BANK_RECONCILE,
    PERMISSIONS.BANK_DAILY_CLOSE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
  ],
  ACCOUNTING: [
    PERMISSIONS.RECEIVABLE_VIEW,
    PERMISSIONS.PAYABLE_VIEW,
    PERMISSIONS.COMMITMENT_VIEW,
    PERMISSIONS.LOAN_VIEW,
    PERMISSIONS.BUDGET_VIEW,
    PERMISSIONS.REVENUE_VIEW,
    PERMISSIONS.BANK_VIEW,
    PERMISSIONS.BANK_RECONCILE,
    PERMISSIONS.BANK_PERIOD_CLOSE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_VIEW,
  ],
  BUDGET: [
    PERMISSIONS.BUDGET_VIEW,
    PERMISSIONS.BUDGET_CREATE,
    PERMISSIONS.BUDGET_ADJUST,
    PERMISSIONS.COMMITMENT_VIEW,
    PERMISSIONS.PAYABLE_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
  ],
  REVENUE: [
    PERMISSIONS.REVENUE_VIEW,
    PERMISSIONS.REVENUE_CREATE,
    PERMISSIONS.REVENUE_EDIT,
    PERMISSIONS.RECEIVABLE_VIEW,
    PERMISSIONS.RECEIVABLE_CREATE,
    PERMISSIONS.RECEIVABLE_PAYMENT,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
  ],
  AUDITOR: [
    PERMISSIONS.RECEIVABLE_VIEW,
    PERMISSIONS.PAYABLE_VIEW,
    PERMISSIONS.COMMITMENT_VIEW,
    PERMISSIONS.LOAN_VIEW,
    PERMISSIONS.BUDGET_VIEW,
    PERMISSIONS.REVENUE_VIEW,
    PERMISSIONS.BANK_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_VIEW,
  ],
  EXECUTIVE: [
    PERMISSIONS.RECEIVABLE_VIEW,
    PERMISSIONS.PAYABLE_VIEW,
    PERMISSIONS.COMMITMENT_VIEW,
    PERMISSIONS.LOAN_VIEW,
    PERMISSIONS.BUDGET_VIEW,
    PERMISSIONS.REVENUE_VIEW,
    PERMISSIONS.BANK_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
  ],
  VIEWER: [
    PERMISSIONS.RECEIVABLE_VIEW,
    PERMISSIONS.PAYABLE_VIEW,
    PERMISSIONS.COMMITMENT_VIEW,
    PERMISSIONS.LOAN_VIEW,
    PERMISSIONS.BUDGET_VIEW,
    PERMISSIONS.REVENUE_VIEW,
    PERMISSIONS.BANK_VIEW,
    PERMISSIONS.REPORT_VIEW,
  ],
};

export function hasPermission(userRole: string, requiredPermission: PermissionCode, customPermissions?: string[]): boolean {
  if (userRole === 'SUPER_ADMIN') return true;
  if (customPermissions && customPermissions.includes(requiredPermission)) return true;
  const rolePermissions = ROLE_DEFAULT_PERMISSIONS[userRole] || [];
  return rolePermissions.includes(requiredPermission);
}
